#!/bin/bash

port=8000
echo "Loading REPL on port $port"
tmux new-window -d -n REPL "cd $1; LEIN_REPL_PORT=$port lein repl"
while ! nc -z localhost $port; do sleep 1; done
tmux split-window -d -h -p 40
tmux select-pane -t1
tmux send-keys "cd $1; lein autoexpect" C-m
tmux select-pane -t0
tmux send-keys "cd $1; vim project.clj" C-m
tmux send-keys ":Connect nrepl://localhost:$port" C-m C-m
tmux send-keys C-p # bring up CtrlP
