#!/bin/bash

port=8000
echo "Loading REPL on port $port"
tmux new-window -d -n REPL
tmux select-window -t :1
tmux send-keys "cd ~/workspace/$1" C-m
tmux send-keys "LEIN_REPL_PORT=$port lein repl" C-m
while ! nc -z localhost $port; do sleep 1; done
tmux new-window -d -n servers
tmux select-window -t :2
tmux send-keys "cd ~/workspace/$1" C-m
tmux send-keys "lein ring server" C-m
tmux select-window -t :0
tmux split-window -d -h -p 40
tmux select-pane -t1
tmux send-keys "cd ~/workspace/$1" C-m
tmux send-keys "lein with-profile test autoexpect" C-m
tmux select-pane -t0
tmux send-keys "cd ~/workspace/$1; \\vim --servername VIM project.clj" C-m
tmux send-keys ":Connect nrepl://localhost:$port" C-m C-m
